apiVersion: v1
kind: ConfigMap
metadata:
  name: api-rest-config
  namespace: filmapi
  labels:
    app.kubernetes.io/name: api-rest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: filmapi-stack
data:
  ENVIRONMENT: "production"
  HOST: "0.0.0.0"
  PORT: "8000"
  WORKERS: "2"
  LOG_LEVEL: "info"
  DATABASE_ECHO: "false"
  DATABASE_POOL_SIZE: "10"
  DATABASE_POOL_RECYCLE: "3600"
  SEED_DATABASE: "false"
  PROJECT_NAME: "API Filmotheque"
  API_V1_STR: "/api/v1"
  HEALTH_CHECK_PATH: "/health"
