apiVersion: v1
kind: Secret
metadata:
  name: api-rest-secret
  namespace: filmapi
  labels:
    app.kubernetes.io/name: api-rest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: filmapi-stack
type: Opaque
stringData:
  # PostgreSQL connection - A CONFIGURER selon votre installation
  DATABASE_URL: "postgresql+asyncpg://filmapi:filmapi@postgres-service:5432/filmapi"
