apiVersion: v1
kind: Service
metadata:
  name: api-rest-service
  namespace: filmapi
  labels:
    app.kubernetes.io/name: api-rest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: filmapi-stack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api-rest
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
